name: CI/CD Pipeline to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Image to ECR
      # 👇 CAMBIA "NombreDeTuCarpetaReal" POR EL NOMBRE EXACTO EN TU GITHUB.
      # (Si no tienes carpetas y los archivos están sueltos, simplemente BORRA esta línea 32)
      working-directory: ./NombreDeTuCarpetaReal
      
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tu-repositorio-ecr-ventas # 👈 Pon tu repositorio de ECR
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to Amazon ECS
      run: |
        aws ecs update-service --cluster solenme-cluster --service service-back-ventas --force-new-deployment --region us-east-1
        # 👆 Revisa que "service-back-ventas" sea el nombre exacto de tu servicio
